services:
  - type: web
    name: salem-game
    env: node
    plan: starter
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    disk:
      name: assets
      mountPath: /opt/render/project/src/dist
      sizeGB: 1 